services:
  open_notebook_single:
    build:
      context: .
      dockerfile: Dockerfile.single
    ports:
      - "3000:3000"  # Next.js UI
      - "5055:5055"  # REST API
      - "8000:8000"  # SurrealDB
    env_file:
      - ./docker.env
    volumes:
      - ./notebook_data:/app/data          # Application data
      - ./surreal_single_data:/mydata      # SurrealDB data
    restart: always
    # Single container includes all services: SurrealDB, API, Worker, and Next.js
    # Access: 
    # - Next.js UI: http://localhost:3000
    # - REST API: http://localhost:5055
    # - API Documentation: http://localhost:5055/docs